<?php
/**
 * DSMP Ecommerce Content
 * /wp-admin/admin.php?page=ds-woo-settings
 */
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_60c08391e8be3',
		'title' => 'Ecommerce Settings',
		'fields' => array(
			array(
				'key' => 'field_60c0839b16077',
				'label' => 'Archive',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_60c0876b718f4',
				'label' => '',
				'name' => 'woo_sidebar',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_60c08755718f3',
						'label' => 'Sidebar',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_60c0840205a6b',
						'label' => 'Sidebar',
						'name' => 'module_view',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'choices' => array(
							'show' => 'show',
							'hide' => 'hide',
						),
						'allow_null' => 0,
						'default_value' => 'hide',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_60c0852205a6c',
						'label' => 'Sidebar position',
						'name' => 'sidebar_position',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c0840205a6b',
									'operator' => '==',
									'value' => 'show',
								),
							),
						),
						'wrapper' => array(
							'width' => '85',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'choices' => array(
							'left' => 'left',
							'right' => 'right',
						),
						'allow_null' => 0,
						'default_value' => 'hide',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
				),
			),
			array(
				'key' => 'field_60c09ca29657c',
				'label' => '',
				'name' => 'woo_filter',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_60c09ca29657d',
						'label' => 'Filter',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_60c09ca29657e',
						'label' => 'Filter',
						'name' => 'module_view',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'choices' => array(
							'show' => 'show',
							'hide' => 'hide',
						),
						'allow_null' => 0,
						'default_value' => 'hide',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
				),
			),
			array(
				'key' => 'field_60c0879b7a313',
				'label' => 'Product',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_60daf44b34e0f',
				'label' => 'Product short description on archive page',
				'name' => 'archive_product_short_description',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'choices' => array(
					'hide' => 'hide',
					'show' => 'show',
				),
				'allow_null' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_60db066eb1df2',
				'label' => 'Single product gallery',
				'name' => 'single_product_gallery',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'choices' => array(
					'vertical' => 'vertical',
					'horizontal' => 'horizontal',
				),
				'allow_null' => 0,
				'default_value' => 'vertical',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_60e824803e6bc',
				'label' => 'Header',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_60c7598340186',
				'label' => 'Cart link',
				'name' => 'cart_link',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'choices' => array(
					'enable' => 'enable',
					'disable' => 'disable',
				),
				'allow_null' => 0,
				'default_value' => 'enable',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_60b4bdecef2ff',
				'label' => 'Cart icon link title',
				'name' => 'cart_icon_link_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_60c7598340186',
							'operator' => '==',
							'value' => 'enable',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'default_value' => 'Cart',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60c75a624018a',
				'label' => 'My Account links',
				'name' => 'my_account_link',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'choices' => array(
					'enable' => 'enable',
					'disable' => 'disable',
				),
				'allow_null' => 0,
				'default_value' => 'enable',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_60b4be05ef300',
				'label' => 'Login icon link title',
				'name' => 'login_icon_link_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_60c75a624018a',
							'operator' => '==',
							'value' => 'enable',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'default_value' => 'Login',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60b4c079f4f08',
				'label' => 'Logout icon link title',
				'name' => 'logout_icon_link_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_60c75a624018a',
							'operator' => '==',
							'value' => 'enable',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'default_value' => 'Logout',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60b4be2def301',
				'label' => 'Register icon link title',
				'name' => 'register_icon_link_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_60c75a624018a',
							'operator' => '==',
							'value' => 'enable',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'default_value' => 'Register',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_60b4bf76a2188',
				'label' => 'Account icon link title',
				'name' => 'account_icon_link_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_60c75a624018a',
							'operator' => '==',
							'value' => 'enable',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'default_value' => 'My Account',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'ds-woo-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;