<?php

/**
 * DSMP Ecommerce Content
 * /wp-admin/admin.php?page=ds-woo-content
 */
if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_60c3691aca40e',
		'title' => 'Ecommerce content',
		'fields' => array(
			array(
				'key' => 'field_60c0879b7a313',
				'label' => 'Product',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_60c345e4b9271',
				'label' => '',
				'name' => 'product_request_a_quote',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_60c345f9b9272',
						'label' => 'Request a quote',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_60c34620b9273',
						'label' => 'Request a quote',
						'name' => 'request_a_quote',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'choices' => array(
							'enable' => 'enable',
						),
						'allow_custom' => 0,
						'default_value' => array(),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_60c3477f8679a',
						'label' => 'Button title',
						'name' => 'button_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34620b9273',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'default_value' => 'Request a quote',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60c3477f867ti',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34620b9273',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60c3477f867su',
						'label' => 'Subtitle',
						'name' => 'subtitle',
						'type' => 'text',
						'instructions' => '',
						'required' => '',
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34620b9273',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60c3477f867ph',
						'label' => 'Phone',
						'name' => 'phone',
						'type' => 'text',
						'instructions' => '',
						'required' => '',
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34620b9273',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60c3477f867te',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => '',
						'required' => '',
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34620b9273',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_625d4b0127072',
						'label' => 'Gravity Form',
						'name' => 'gravity_form',
						'type' => 'forms',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34620b9273',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'return_format' => 'id',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
			),
			array(
				'key' => 'field_60c34a0689784',
				'label' => '',
				'name' => 'product_cta_banner',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_60c34a0689785',
						'label' => 'CTA Banner',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_60c34a0689786',
						'label' => 'CTA Banner',
						'name' => 'cta_banner',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'choices' => array(
							'enable' => 'enable',
						),
						'allow_custom' => 0,
						'default_value' => array(),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_60c34a5c89789',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34a0689786',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60c34a6f8978a',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34a0689786',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 4,
						'new_lines' => 'wpautop',
					),
					array(
						'key' => 'field_60c34a858978b',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'link',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34a0689786',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'return_format' => 'array',
					),
					array(
						'key' => 'field_60c34aa28978c',
						'label' => 'Background image',
						'name' => 'background_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_60c34a0689786',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'return_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
			array(
				'key' => 'field_60c34sp689784',
				'label' => '',
				'name' => 'shipping_bar',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_60c34sp689785',
						'label' => 'Shipping Bar',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_625ec1dde0157',
						'label' => 'Shipping bar',
						'name' => 'shipping_bar',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'choices' => array(
							'enable' => 'enable',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_70e800801e6bc',
						'label' => 'Is sticky?',
						'name' => 'shipping_is_sticky',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_625ec1dde0157',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'choices' => array(
							'enable' => 'enable',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_70e800802e6bc',
						'label' => 'Shipping position',
						'name' => 'shipping_position',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_70e800801e6bc',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'ds_default_value' => 0,
						'choices' => array(
							'left' => 'left',
							'right' => 'right',
						),
						'allow_null' => 0,
						'default_value' => 'right',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_70e800803e6bc',
						'label' => 'Is expendable?',
						'name' => 'shipping_expendable',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_70e800801e6bc',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'choices' => array(
							'enable' => 'enable',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_625ec215e0158',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_625ec1dde0157',
									'operator' => '==',
									'value' => 'enable',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'ds_asset_type' => '',
						'collapsed' => '',
						'min' => 1,
						'max' => 0,
						'layout' => 'block',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_625ec22be0159',
								'label' => 'Icon',
								'name' => 'icon',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '20',
									'class' => '',
									'id' => '',
								),
								'ds_asset_type' => '',
								'return_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_625ec236e015a',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30',
									'class' => '',
									'id' => '',
								),
								'ds_asset_type' => '',
								'ds_default_value' => 0,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_625ec243e015b',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30',
									'class' => '',
									'id' => '',
								),
								'ds_asset_type' => '',
								'ds_default_value' => 0,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_625ec24ce015c',
								'label' => 'Link',
								'name' => 'link',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '20',
									'class' => '',
									'id' => '',
								),
								'ds_asset_type' => '',
								'return_format' => 'array',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_60c9bf2309b5a',
				'label' => 'Shop',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_60c9bf2c09b5b',
				'label' => 'Subheader image',
				'name' => 'shop_background',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_629ti41f7shop',
				'label' => 'Page Title',
				'name' => 'shop_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => '',
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_629su41f7shop',
				'label' => 'Page Subtitle',
				'name' => 'shop_subtitle',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => '',
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'ds_asset_type' => '',
				'ds_default_value' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'ds-woo-content',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;
